// src/HumanHead.jsx
/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Source: https://sketchfab.com/3d-models/human-head-926ba74256cf463c920afc1fdc8bc6ae
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function HumanHead(props) {
  const { nodes, materials } = useGLTF('/models/humanHead.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.003, 2.279, -0.051]} rotation={[Math.PI / 2, 0, 0.227]} scale={0.249}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['Scene_-_Root']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/humanHead.glb')
